config/routes.rb
Rails.application.routes.draw do
  root to: 'alexa_top_sites#index'

  resources :alexa_top_sites, only: [:index, :edit, :update]
end

app/models/alexa_top_site.rb
class AlexaTopSite < ActiveRecord::Base
  validates :url, :rank, presence: true

  mount_uploader :screenshot, ScreenshotUploader
end

app/controllers/alexa_top_sites_controller.rb
class AlexaTopSitesController < ApplicationController
  before_action :find_alexa_top_site, only: [:edit, :update]

  def index
    @top_sites = AlexaTopSite.limit(params.fetch(:limit, 100))
  end

  def edit
    render 'edit', layout: false
  end

  def update
    if @alexa_top_site.update(top_site_params)
      flash.now[:success] = 'Record saved successfully'
    end
    render 'edit', layout: false
  end

  private

  def find_alexa_top_site
    @alexa_top_site = AlexaTopSite.find(params[:id])
  end

  def top_site_params
    params.require(:alexa_top_site).permit(:url, :page_views_per_million, :page_views_per_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alexa_top_sites/_form.haml
.modal-body
  = simple_form_for @alexa_top_site, remote: true, html: { style: 'display:inline;',
    'data-update-target' => '#alexa-top-site-modal .modal-content', 'data-type' => 'text' } do |f|
    - flash.each do |key, value|
      .alert{ class: "alert-#{key}", role: 'alert' }= value

    = f.input :rank, disabled: true
    = f.input :url
    = f.input :page_views_per_million
    = f.input :page_views_per_user

    = f.submit 'Save', class: 'btn btn-primary'
    = link_to 'Cancel', '#', class: 'btn', data: { dismiss: 'modal' }

app/views/alexa_top_sites/_top_site.haml
%tr
  %td= top_site.rank
  %td= top_site.url
  %td= top_site.page_views_per_million
  %td= top_site.page_views_per_user
  %td
    = link_to edit_alexa_top_site_path(top_site), remote: true, 'data-type' => 'text', title: 'Edit',
              'data-update-target' => '#alexa-top-site-modal .modal-content',
              'data-target' => '#alexa-top-site-modal', 'data-toggle' => 'modal' do
      %span.glyphicon.glyphicon-edit{ 'aria-hidden' => 'true' }
    &nbsp;
    %span.glyphicon.glyphicon-eye-open{ 'aria-hidden' => 'true','data-toggle' => 'popover', 'data-trigger' => 'hover',
                                        'data-placement' => 'left', 'data-screenshot-url' => top_site.screenshot_url }

app/views/alexa_top_sites/edit.haml
.modal-header
  %button{ type: 'button', class: 'close', 'data-dismiss' => 'modal', 'aria-label' => 'Close' }
    %span{ 'aria-hidden' => 'true' } &times;
  %h3= "Editing #{@alexa_top_site.url}"
= render 'form'

app/views/alexa_top_sites/index.haml
%h3 Alexa Top 100 Sites

%table#alexa-top-sites.table.table-striped.table-hover.table-condensed
  %thead
    %tr
      %th Rank
      %th Site
      %th Page Views / Million
      %th Page Views / User
      %th.actions
  %tbody
    = render partial: 'top_site', collection: @top_sites

#alexa-top-site-modal.modal.fade{ role: 'dialog' }
  .modal-dialog{ role: 'document' }
    .modal-content

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BuzzstarterChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>